language: python
python: 
  - "3.8"
before_install:
  - sudo apt update
  - sudo apt install texlive-base dvipng texlive-latex-base
  - pip install -rtest/requirements.txt
script:
  - python test/test.py

